Adding libvirtd to rc.local for starting it on boot up

diff --git a/baadalinstallation/pxe_host_setup/host_installation_sh b/baadalinstallation/pxe_host_setup/host_installation_sh
--- a/baadalinstallation/pxe_host_setup/host_installation_sh
+++ b/baadalinstallation/pxe_host_setup/host_installation_sh
@@ -57,8 +57,12 @@ Enbl_Modules()
 	./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc --with-esx=yes
 	make
 	make install
-
-	/etc/init.d/libvirtd restart
+	/usr/sbin/libvirtd -d 
+	if test $? -ne 0; then
+		echo "Unable to start libvirtd. Check installation and try again"
+		exit $?
+	fi
+	sed -i -e "s@exit 0@/usr/sbin/libvirtd -d\nexit 0@" /etc/rc.local
 
 	#CREATE LIBVIRT NETWORK
 	virsh net-destroy default
